package com.citrix.pageobjects;

//Autogenerated page object class
public class LoginPO {

	
	public String getUSERNAMELOCATOR(){
		return "id";
	}

	public String getPASSWORDLOCATOR(){
		return "id";
	}
	public String getSUBMITLOCATOR(){
		return "id";
	}
	
	public String getUSERNAMEVALUE(){
		return "emailAddress";
	}

	public String getPASSWORDVALUE(){
		return "password";
	}
	public String getSUBMITVALUE(){
		return "submit";
	}
}
